### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Stone-Red-Code** [TwiN/.github#2]
### Describe the bug

# TwiN

### What do you see?

Uh yeah

### What do you expect to see?

nice feature

### List the steps that must be taken to reproduce this issue

1. I
2. Just
3. Wanted
4. To
5. Say
6. Hi

### Version

0.1

### Additional information

_Sorry TwiN_

**Comment by TwiN** [comment]
Thank you for your feedback, stone 😩
